services:
  proxy:
    build:
      dockerfile: applications/proxy/Dockerfile
    depends_on:
      server:
        condition: service_healthy
      web:
        condition: service_healthy
      docs:
        condition: service_healthy
    environment:
      WEB_PORT: 3000
      WEB_HOST: ${SERVICE_NAME_WEB}
      SERVER_HOST: ${SERVICE_NAME_SERVER}
      DOCS_HOST: ${SERVICE_NAME_DOCS}
      DOCS_PORT: 80
      FRONTEND_URL: ${SERVICE_URL_PROXY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  server:
    build:
      dockerfile: applications/server/Dockerfile
    environment:
      NODE_ENV: production
      LOG_LEVEL: ${LOG_LEVEL:-Info}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${SERVICE_FQDN_PROXY}
      DATABASE_MAIN: postgres
      DATABASE_USER: sideline
      DATABASE_PASS: ${DATABASE_PASSWORD}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT: https://sideline-preview.majksa.net/api
      API_PREFIX: /api
      RPC_PREFIX: /rpc/sync
      FRONTEND_URL: ${SERVICE_URL_PROXY}
      SERVER_URL: ${SERVICE_URL_PROXY}/api
      APP_ENV: preview
      APP_ORIGIN: ${SERVICE_FQDN_PROXY}
      APP_GLOBAL_ADMIN_DISCORD_IDS: "635530520125767750"
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otelcollectorhttp-ccogw4cogg00wwowc0s4c0cs.majksa.net/
      OTEL_SERVICE_NAME: sideline-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 30s
  bot:
    build:
      dockerfile: applications/bot/Dockerfile
    depends_on:
      server:
        condition: service_healthy
    environment:
      NODE_ENV: production
      LOG_LEVEL: ${LOG_LEVEL:-Info}
      SERVER_URL: http://${SERVICE_NAME_SERVER}:80
      RPC_PREFIX: /rpc/sync
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      APP_ENV: preview
      APP_ORIGIN: ${SERVICE_FQDN_PROXY}
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otelcollectorhttp-ccogw4cogg00wwowc0s4c0cs.majksa.net/
      OTEL_SERVICE_NAME: sideline-bot
      WEB_URL: ${SERVICE_URL_PROXY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  web:
    build:
      dockerfile: applications/web/Dockerfile
    depends_on:
      server:
        condition: service_healthy
    environment:
      SERVER_URL: ${SERVICE_URL_PROXY}/api
      PORT: 3000
      WEB_URL: ${SERVICE_URL_PROXY}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${SERVICE_URL_PROXY}/otel
      OTEL_SERVICE_NAME: sideline-web
      APP_ENV: preview
      APP_ORIGIN: ${SERVICE_FQDN_PROXY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  docs:
    build:
      dockerfile: applications/docs/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
