import {
  AchievementApi,
  ActivityLogApi,
  ActivityStatsApi,
  ActivityTypeApi,
  AgeThresholdApi,
  Auth,
  DashboardApi,
  EventApi,
  EventRsvpApi,
  EventSeriesApi,
  FinanceApi,
  GroupApi,
  ICalApi,
  Invite,
  LeaderboardApi,
  NotificationApi,
  RoleApi,
  Roster,
  TeamApi,
  TeamSettingsApi,
  TrainingTypeApi,
  Translations,
  VersionApi,
  WeeklySummaryApi,
} from '@sideline/domain';
import { HttpApi } from 'effect/unstable/httpapi';
import { env } from '~/env.js';

export const Api = HttpApi.make('api')
  .add(
    AchievementApi.AchievementApiGroup,
    ActivityLogApi.ActivityLogApiGroup,
    ActivityStatsApi.ActivityStatsApiGroup,
    ActivityTypeApi.ActivityTypeApiGroup,
    LeaderboardApi.LeaderboardApiGroup,
    AgeThresholdApi.AgeThresholdApiGroup,
    Auth.AuthApiGroup,
    DashboardApi.DashboardApiGroup,
    EventApi.EventApiGroup,
    EventRsvpApi.EventRsvpApiGroup,
    EventSeriesApi.EventSeriesApiGroup,
    FinanceApi.FinanceApiGroup,
    GroupApi.GroupApiGroup,
    ICalApi.ICalApiGroup,
    Invite.InviteApiGroup,
    NotificationApi.NotificationApiGroup,
    Roster.RosterApiGroup,
    RoleApi.RoleApiGroup,
    TeamApi.TeamApiGroup,
    TeamSettingsApi.TeamSettingsApiGroup,
    TrainingTypeApi.TrainingTypeApiGroup,
    Translations.TranslationsApiGroup,
    VersionApi.VersionApiGroup,
    WeeklySummaryApi.WeeklySummaryApiGroup,
  )
  .prefix(env.API_PREFIX as '/${string}');
