// TDD mode — tests written BEFORE `CommandPalette` and `~/components/ui/command` exist. This
// file WILL FAIL to even import until both land:
//   - `applications/web/src/components/organisms/CommandPalette.tsx`
//   - `applications/web/src/components/ui/command.tsx` (generated by
//     `pnpm -C ./applications/web dlx shadcn@latest add command`, which also adds `cmdk` to
//     `package.json`)
//
// Plan `.work-plans/command-palette-search.md` §C/§F.6, design
// `.work-plans/command-palette-search-design.md` §3 (open/close/states), §4 (rows reuse
// `AssistantResultCard`), §5 (grouping/keyboard), §6 (the Ask row), §8 (accessibility).
//
// Contract under test (design §10 / plan §C):
//   CommandPalette({
//     teamId: string;
//     open: boolean;
//     onOpenChange: (open: boolean) => void;
//     onSelectHit: (hit: AiChatApi.SearchHit) => void;   // parent navigates
//     onAskAssistant: (question: string) => void;        // parent navigates
//   })
//
// The organism owns NO `open` state and calls no router hook (AGENTS.md:26) — `open`/
// `onOpenChange` are driven by this test, exactly as the layout will drive them in production.
// `onSelectHit` / `onAskAssistant` are spies; this file does NOT assert the per-kind `navigate()`
// call the plan's §F.6 row 15/16 describe "at the layout level" — that switch lives in
// `AuthenticatedLayout.tsx`, which is out of scope for this test file (see the report for why).
//
// The mocked-client blind spot (plan §F.6, closing paragraph): the result-rendering tests build
// fixtures with REAL `Schema.Class` constructors (`EventApi.EventInfo`, `GroupApi.GroupInfo`,
// `Roster.RosterInfo`, `TrainingTypeApi.TrainingTypeInfo` — membership is NOMINAL, a
// field-for-field plain object fails to encode, `chatMessages.test.ts` / `SearchApi.test.ts`
// document the precedent), then round-trip them through
// `Schema.encodeSync(Schema.Array(SearchApi.SearchHit))` and back through
// `Schema.decodeUnknownSync` before handing them to the mocked `api.search.search`, so a decode
// bug in the real wire format cannot hide behind a mock that only returns what was handed to it.

import {
  type AiChatApi,
  EventApi,
  GroupApi,
  Roster,
  SearchApi,
  TrainingTypeApi,
} from '@sideline/domain';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { DateTime, Effect, Option, Schema } from 'effect';
import type React from 'react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ---------------------------------------------------------------------------
// jsdom polyfills cmdk needs (plan §F.6 setup notes)
// ---------------------------------------------------------------------------

// cmdk scrolls the highlighted row into view on every highlight change; jsdom does not
// implement `scrollIntoView` at all, and every keyboard test would throw without this.
window.HTMLElement.prototype.scrollIntoView = vi.fn();

// ---------------------------------------------------------------------------
// Module mocks — must be declared before dynamic imports
// ---------------------------------------------------------------------------

// An explicit, FINITE map — never an identity fallback for the known keys. If the component
// ever computes a key (e.g. a template literal over `kind` instead of an explicit per-kind
// lookup), the computed key misses this map, falls through to the raw-key fallback below, and
// trips the "no raw search_/assistant_ key leaks into the DOM" assertion in the results test.
const TR_MAP: Record<string, string> = {
  search_title: 'Search',
  search_description: 'Search description copy',
  search_placeholder: 'Search placeholder copy',
  search_hint: 'Search hint copy',
  search_loading: 'Search loading copy',
  search_noResults: 'No matches for "{query}"',
  search_error: 'Search error copy',
  search_resultCount: '{count} results copy',
  search_askAssistant: 'Ask the assistant: "{query}"',
  search_askAssistantAbout: 'Ask the assistant about "{query}"',
  event_events: 'Events',
  team_members: 'Members',
  team_groups: 'Groups',
  team_rosters: 'Rosters',
  team_trainingTypes: 'Training Types',
  error_offline: 'You are offline',
  assistant_result_event: 'Event kind',
  assistant_result_member: 'Member kind',
  assistant_result_group: 'Group kind',
  assistant_result_roster: 'Roster kind',
  assistant_result_trainingType: 'Training type kind',
  group_memberCount: 'members count copy',
  roster_memberCount: 'roster members count copy',
  roster_active: 'On roster',
  roster_inactive: 'Off roster',
  trainingType_noGroup: 'Everyone',
  event_allDayLabel: 'Full day',
  event_status_active: 'Confirmed',
  event_status_cancelled: 'Called off',
  event_status_started: 'Underway',
  event_type_training: 'Practice',
  event_type_match: 'Match day',
  event_type_tournament: 'Tournament',
  event_type_meeting: 'Meeting',
  event_type_social: 'Social',
  event_type_other: 'Other',
};

function interpolate(template: string, params?: Record<string, unknown>): string {
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (whole: string, key: string) =>
    params[key] === undefined ? whole : String(params[key]),
  );
}

vi.mock('~/lib/translations.js', () => ({
  tr: (key: string, params?: Record<string, unknown>) => interpolate(TR_MAP[key] ?? key, params),
  setTranslationOverrides: vi.fn(),
}));

vi.mock('~/hooks/use-mobile.js', () => ({
  useIsMobile: vi.fn(() => false),
}));

// Radix `Avatar.Image` never fires a load event in jsdom — same workaround as
// `AssistantResultCard.test.tsx` / `AssistantConversation.test.tsx`, needed here because the
// palette renders member rows through the real `AssistantResultCard`.
vi.mock('~/components/ui/avatar', () => ({
  Avatar: ({ children, ...rest }: React.PropsWithChildren<Record<string, unknown>>) => (
    <div data-slot='avatar' {...rest}>
      {children}
    </div>
  ),
  AvatarImage: (props: React.ImgHTMLAttributes<HTMLImageElement>) => (
    // biome-ignore lint/a11y/useAltText: alt is forwarded via {...props} from the real caller
    <img data-slot='avatar-image' {...props} />
  ),
  AvatarFallback: ({ children, ...rest }: React.PropsWithChildren<Record<string, unknown>>) => (
    <span data-slot='avatar-fallback' {...rest}>
      {children}
    </span>
  ),
}));

// `AssistantResultCard`'s default (non-`renderWrapper`) branch imports `Link` at module scope,
// so it must be mocked even though the palette itself never renders that branch (it always
// passes `renderWrapper`, per design §4). Self-contained (no captured outer variables — safe
// under `vi.mock` hoisting), same idiom as `AssistantResultCard.test.tsx`.
vi.mock('@tanstack/react-router', () => ({
  Link: ({
    to,
    params,
    children,
    ...rest
  }: React.PropsWithChildren<{ to: string; params?: Record<string, unknown> }>) => {
    const href = String(to).replace(/\$([a-zA-Z]+)/g, (whole: string, key: string) =>
      params && key in params ? String(params[key]) : whole,
    );
    return (
      <a href={href} {...rest}>
        {children}
      </a>
    );
  },
}));

// `mockSearch` stands in for the generated client's `api.search.search(...)` — the one call
// this organism makes (Pattern C, `applications/web/AGENTS.md:831`). `mockRun` really executes
// the piped Effect via `Effect.option` (mirrors `runPromiseClient`'s shape minus toast side
// effects), matching `AssistantConversation.test.tsx`'s precedent.
const { mockSearch } = vi.hoisted(() => ({ mockSearch: vi.fn() }));

const mockRun = () => (effect: Effect.Effect<unknown, unknown>) =>
  Effect.runPromise(Effect.option(effect));

vi.mock('~/lib/runtime', () => ({
  ApiClient: { asEffect: () => Effect.succeed({ search: { search: mockSearch } }) },
  ClientError: { make: (message: string) => ({ _tag: 'ClientError', message }) },
  SilentClientError: class SilentClientError {
    readonly _tag = 'SilentClientError';
    props: { message: string };
    constructor(props: { message: string }) {
      this.props = props;
    }
  },
  useRun: () => mockRun,
}));

// Dynamic import AFTER mocks — will fail until CommandPalette (and ui/command, and cmdk) exist.
const { CommandPalette } = await import('~/components/organisms/CommandPalette.js');

// ---------------------------------------------------------------------------
// Fixtures — real `Schema.Class` instances, mirroring `packages/domain/test/SearchApi.test.ts`.
// ---------------------------------------------------------------------------

const TEAM_ID = 'team-1';

let idCounter = 0;
const nextId = (prefix: string) => `${prefix}-${idCounter++}`;

function eventHit(overrides: { title?: string; eventId?: string } = {}): AiChatApi.SearchHit {
  const eventId = overrides.eventId ?? nextId('event');
  return {
    kind: 'event',
    event: new EventApi.EventInfo({
      eventId: eventId as any,
      teamId: TEAM_ID as any,
      title: overrides.title ?? `Event ${eventId}`,
      eventType: 'training',
      trainingTypeName: Option.none(),
      eventTypeId: Option.none() as any,
      eventTypeName: Option.none<Option.Option<string>>(),
      eventTypeColor: Option.none() as any,
      description: Option.none(),
      imageUrl: Option.none(),
      startAt: DateTime.makeUnsafe('2026-05-12T18:00:00.000Z'),
      endAt: Option.some(DateTime.makeUnsafe('2026-05-12T19:30:00.000Z')),
      location: Option.none(),
      locationUrl: Option.none(),
      status: 'active',
      allDay: false,
      seriesId: Option.none(),
      startDate: Option.some('2026-05-12'),
      endDate: Option.some('2026-05-12'),
    }),
  };
}

function memberHit(
  overrides: { displayName?: string; memberId?: string } = {},
): AiChatApi.SearchHit {
  const memberId = overrides.memberId ?? nextId('member');
  return {
    kind: 'member',
    memberId: memberId as any,
    displayName: overrides.displayName ?? `Member ${memberId}`,
    avatarUrl: Option.none(),
    jerseyNumber: Option.none(),
    roleNames: [],
    effectiveRoles: [],
    active: true,
  };
}

function groupHit(overrides: { name?: string; groupId?: string } = {}): AiChatApi.SearchHit {
  const groupId = overrides.groupId ?? nextId('group');
  return {
    kind: 'group',
    group: new GroupApi.GroupInfo({
      groupId: groupId as any,
      teamId: TEAM_ID as any,
      parentId: Option.none(),
      name: overrides.name ?? `Group ${groupId}`,
      emoji: Option.none(),
      color: Option.none(),
      memberCount: 10,
      discordChannelProvisioning: false,
    }),
  };
}

function rosterHit(overrides: { name?: string; rosterId?: string } = {}): AiChatApi.SearchHit {
  const rosterId = overrides.rosterId ?? nextId('roster');
  return {
    kind: 'roster',
    roster: new Roster.RosterInfo({
      rosterId: rosterId as any,
      teamId: TEAM_ID as any,
      name: overrides.name ?? `Roster ${rosterId}`,
      active: true,
      memberCount: 15,
      createdAt: '2026-01-01T00:00:00.000Z',
      color: Option.none(),
      emoji: Option.none(),
      discordChannelId: Option.none(),
      discordChannelName: Option.none(),
      discordChannelProvisioning: false,
    }),
  };
}

function trainingTypeHit(
  overrides: { name?: string; trainingTypeId?: string } = {},
): AiChatApi.SearchHit {
  const trainingTypeId = overrides.trainingTypeId ?? nextId('tt');
  return {
    kind: 'trainingType',
    trainingType: new TrainingTypeApi.TrainingTypeInfo({
      trainingTypeId: trainingTypeId as any,
      teamId: TEAM_ID as any,
      name: overrides.name ?? `Training ${trainingTypeId}`,
      ownerGroupName: Option.none(),
      memberGroupName: Option.none(),
    }),
  };
}

// The guard the plan's §F.6 closing paragraph demands: round-trip every fixture array through
// the REAL wire schema before handing it to the mock, so a decode bug cannot hide behind a mock
// that trivially returns whatever it was given.
function hitsThroughWire(
  hits: ReadonlyArray<AiChatApi.SearchHit>,
): ReadonlyArray<AiChatApi.SearchHit> {
  const encoded = Schema.encodeSync(Schema.Array(SearchApi.SearchHit))(hits);
  return Schema.decodeUnknownSync(Schema.Array(SearchApi.SearchHit))(encoded);
}

// ---------------------------------------------------------------------------
// Render helpers
// ---------------------------------------------------------------------------

interface Props {
  teamId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSelectHit: (hit: AiChatApi.SearchHit) => void;
  onAskAssistant: (question: string) => void;
}

function setup(
  overrides: Partial<Omit<Props, 'onOpenChange' | 'onSelectHit' | 'onAskAssistant'>> = {},
) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  const onOpenChange = vi.fn();
  const onSelectHit = vi.fn();
  const onAskAssistant = vi.fn();
  const baseProps: Props = {
    teamId: TEAM_ID,
    open: true,
    onOpenChange,
    onSelectHit,
    onAskAssistant,
    ...overrides,
  };

  const utils = render(
    <QueryClientProvider client={client}>
      <CommandPalette {...baseProps} />
    </QueryClientProvider>,
  );

  const rerenderWith = (next: Partial<Props>) => {
    const merged = { ...baseProps, ...next };
    utils.rerender(
      <QueryClientProvider client={client}>
        <CommandPalette {...merged} />
      </QueryClientProvider>,
    );
  };

  return { ...utils, client, onOpenChange, onSelectHit, onAskAssistant, rerenderWith };
}

function getInput(): HTMLInputElement {
  return screen.getByRole('combobox') as HTMLInputElement;
}

async function typeQuery(value: string) {
  fireEvent.change(getInput(), { target: { value } });
}

async function settle(ms = 250) {
  await act(async () => {
    await vi.advanceTimersByTimeAsync(ms);
  });
}

beforeEach(() => {
  idCounter = 0;
  mockSearch.mockReset();
});

afterEach(() => {
  vi.useRealTimers();
  document.body.removeAttribute('data-scroll-locked');
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('CommandPalette', () => {
  describe('hotkey (F.6/1-6)', () => {
    it('Cmd+K opens the palette', () => {
      const { onOpenChange } = setup({ open: false });
      fireEvent.keyDown(window, { key: 'k', metaKey: true });
      expect(onOpenChange).toHaveBeenCalledWith(true);
    });

    it('Ctrl+K opens the palette', () => {
      const { onOpenChange } = setup({ open: false });
      fireEvent.keyDown(window, { key: 'k', ctrlKey: true });
      expect(onOpenChange).toHaveBeenCalledWith(true);
    });

    it('a bare "k" with no modifier does nothing', () => {
      const { onOpenChange } = setup({ open: false });
      fireEvent.keyDown(window, { key: 'k' });
      expect(onOpenChange).not.toHaveBeenCalled();
    });

    it('metaKey + shiftKey does nothing (extra modifier disqualifies the chord)', () => {
      const { onOpenChange } = setup({ open: false });
      fireEvent.keyDown(window, { key: 'k', metaKey: true, shiftKey: true });
      expect(onOpenChange).not.toHaveBeenCalled();
    });

    it('does nothing while another modal owns the screen (body[data-scroll-locked]) and the palette is closed', () => {
      document.body.setAttribute('data-scroll-locked', '');
      const { onOpenChange } = setup({ open: false });
      fireEvent.keyDown(window, { key: 'k', metaKey: true });
      expect(onOpenChange).not.toHaveBeenCalled();
    });

    it('the scroll-locked guard does not block CLOSING an already-open palette', () => {
      document.body.setAttribute('data-scroll-locked', '');
      const { onOpenChange } = setup({ open: true });
      fireEvent.keyDown(window, { key: 'k', metaKey: true });
      expect(onOpenChange).toHaveBeenCalledWith(false);
    });

    it('Escape closes the palette (Radix Dialog default) by requesting onOpenChange(false)', () => {
      const { onOpenChange } = setup({ open: true });
      expect(screen.getByRole('dialog')).not.toBeNull();
      fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' });
      expect(onOpenChange).toHaveBeenCalledWith(false);
    });
  });

  describe('states (F.6/7-10, F.6/18-19, design §6.1)', () => {
    it('below the 2-character floor: no request is issued and the hint renders, but a 1-char query still shows the Ask row', async () => {
      vi.useFakeTimers();
      setup();
      await typeQuery('a');
      await settle();

      expect(mockSearch).not.toHaveBeenCalled();
      expect(screen.getByText(TR_MAP.search_hint)).not.toBeNull();
      // "The Ask row appears at one character" (design §6.1 / plan §F.6 extra assertion #2).
      expect(
        screen.getByText(interpolate(TR_MAP.search_askAssistantAbout, { query: 'a' })),
      ).not.toBeNull();
    });

    it('an empty query shows no Ask row at all', () => {
      setup();
      expect(screen.queryByText(interpolate(TR_MAP.search_askAssistant, { query: '' }))).toBeNull();
      expect(
        screen.queryByText(interpolate(TR_MAP.search_askAssistantAbout, { query: '' })),
      ).toBeNull();
    });

    it('debounces to exactly one request for a term typed one character at a time', async () => {
      vi.useFakeTimers();
      mockSearch.mockReturnValueOnce(Effect.succeed([]));
      setup();

      let value = '';
      for (const ch of 'alpha') {
        value += ch;
        await typeQuery(value);
        await settle(50); // well under the 250ms debounce — each keystroke resets the timer
      }
      await settle(250);

      expect(mockSearch).toHaveBeenCalledTimes(1);
      const call = mockSearch.mock.calls[0]?.[0];
      expect(call.query).toEqual({ q: 'alpha' });
    });

    it('shows the loading state while the request is in flight', async () => {
      vi.useFakeTimers();
      mockSearch.mockReturnValueOnce(Effect.never);
      setup();
      await typeQuery('ab');
      await settle();

      expect(screen.getByText(TR_MAP.search_loading)).not.toBeNull();
    });

    it('zero results renders the no-matches copy AND the Ask row', async () => {
      vi.useFakeTimers();
      mockSearch.mockReturnValueOnce(Effect.succeed([]));
      setup();
      await typeQuery('zzz');
      await settle();

      await waitFor(
        () => {
          expect(
            screen.getByText(interpolate(TR_MAP.search_noResults, { query: 'zzz' })),
          ).not.toBeNull();
        },
        { timeout: 2000, interval: 50 },
      );
      expect(
        screen.getByText(interpolate(TR_MAP.search_askAssistantAbout, { query: 'zzz' })),
      ).not.toBeNull();
    });

    it('offline: no request is issued, the offline copy renders, and the Ask row is hidden', async () => {
      vi.useFakeTimers();
      const onLineSpy = vi.spyOn(window.navigator, 'onLine', 'get').mockReturnValue(false);
      try {
        setup();
        await typeQuery('alpha');
        await settle();

        expect(mockSearch).not.toHaveBeenCalled();
        expect(screen.getByText(TR_MAP.error_offline)).not.toBeNull();
        expect(
          screen.queryByText(interpolate(TR_MAP.search_askAssistant, { query: 'alpha' })),
        ).toBeNull();
        expect(
          screen.queryByText(interpolate(TR_MAP.search_askAssistantAbout, { query: 'alpha' })),
        ).toBeNull();
      } finally {
        onLineSpy.mockRestore();
      }
    });

    it('a rejected request renders the error copy, keeps the dialog open, and still shows the Ask row', async () => {
      vi.useFakeTimers();
      mockSearch.mockReturnValueOnce(Effect.fail(new Error('boom')));
      setup();
      await typeQuery('alpha');
      await settle();

      await waitFor(() => {
        expect(screen.getByText(TR_MAP.search_error)).not.toBeNull();
      });
      expect(screen.getByRole('dialog')).not.toBeNull();
      expect(
        screen.getByText(interpolate(TR_MAP.search_askAssistantAbout, { query: 'alpha' })),
      ).not.toBeNull();
    });
  });

  describe('results and grouping (F.6/11-13, permissions §7)', () => {
    it('renders all five plural group headings and a row per kind, with no raw search_/assistant_ key ever in the DOM', async () => {
      vi.useFakeTimers();
      const hits = hitsThroughWire([
        eventHit({ title: 'Tuesday training' }),
        memberHit({ displayName: 'Jan Novák' }),
        groupHit({ name: 'U20' }),
        rosterHit({ name: 'First team' }),
        trainingTypeHit({ name: 'Speed' }),
      ]);
      mockSearch.mockReturnValueOnce(Effect.succeed(hits));
      const { container } = setup();
      // Two characters, not one: the dedicated floor test above pins that a 1-char query
      // issues no request at all, so a 1-char query here could never produce these rows.
      await typeQuery('ev');
      await settle();

      await waitFor(() => {
        expect(screen.getByText('Tuesday training')).not.toBeNull();
      });

      for (const heading of [
        TR_MAP.event_events,
        TR_MAP.team_members,
        TR_MAP.team_groups,
        TR_MAP.team_rosters,
        TR_MAP.team_trainingTypes,
      ]) {
        expect(screen.getByText(heading)).not.toBeNull();
      }
      expect(screen.getByText('Jan Novák')).not.toBeNull();
      expect(screen.getByText('U20')).not.toBeNull();
      expect(screen.getByText('First team')).not.toBeNull();
      expect(screen.getByText('Speed')).not.toBeNull();

      expect(container.textContent).not.toMatch(/\bsearch_[a-zA-Z]+\b/);
      expect(container.textContent).not.toMatch(/\bassistant_[a-zA-Z]+\b/);
    });

    it('a result set with no group hits renders no "Groups" heading, and no visible count appears anywhere (partial results read as normal, design §7)', async () => {
      vi.useFakeTimers();
      const hits = hitsThroughWire([eventHit({ title: 'Only an event' })]);
      mockSearch.mockReturnValueOnce(Effect.succeed(hits));
      setup();
      await typeQuery('only');
      await settle();

      await waitFor(() => {
        expect(screen.getByText('Only an event')).not.toBeNull();
      });

      expect(screen.queryByText(TR_MAP.team_groups)).toBeNull();
      expect(screen.queryByText(TR_MAP.team_members)).toBeNull();
      expect(screen.queryByText(TR_MAP.team_rosters)).toBeNull();
      expect(screen.queryByText(TR_MAP.team_trainingTypes)).toBeNull();

      // The heading that IS present carries no parenthetical/appended count — the sr-only
      // resultCount lives only in the live region, asserted separately below.
      expect(screen.getByText(TR_MAP.event_events).textContent).toBe(TR_MAP.event_events);

      // No visible (non-`aria-live`) count string anywhere in the dialog.
      const liveRegion = document.querySelector('[aria-live]');
      const dialog = screen.getByRole('dialog');
      const visibleNodes = Array.from(dialog.querySelectorAll('*')).filter(
        (el) => el !== liveRegion && !(liveRegion?.contains(el) ?? false),
      );
      for (const node of visibleNodes) {
        const ownText = Array.from(node.childNodes)
          .filter((n) => n.nodeType === Node.TEXT_NODE)
          .map((n) => n.textContent ?? '')
          .join('');
        expect(ownText).not.toMatch(/\d+\s*(results?|of\s+\d+)/i);
      }
    });

    it('shouldFilter={false} guard: a hit still renders even though cmdk would score its explicit value={kind:id}, not the visible text, against the query', async () => {
      vi.useFakeTimers();
      // The row's own PRIMARY text is made identical to the query, which would matter only if
      // cmdk were scoring rendered text — proving the row survives regardless demonstrates that
      // scoring is not happening against text at all (it is disabled via `shouldFilter`), since
      // the item's cmdk `value` is `member:<uuid>`, which never contains "Nováková".
      const hits = hitsThroughWire([memberHit({ displayName: 'Nováková' })]);
      mockSearch.mockReturnValueOnce(Effect.succeed(hits));
      setup();
      await typeQuery('Nováková');
      await settle();

      await waitFor(() => {
        expect(screen.getByText('Nováková')).not.toBeNull();
      });
    });
  });

  describe('keyboard selection (F.6/14-15)', () => {
    // The Ask row is always an item once something is typed, so a single hit means two
    // items, not one — ArrowDown moves onto the Ask row rather than wrapping. Enter with
    // no ArrowDown is what selects the hit, and that is the behaviour worth pinning.
    it('Enter selects the first hit', async () => {
      vi.useFakeTimers();
      const hit = eventHit({ title: 'The only hit' });
      mockSearch.mockReturnValueOnce(Effect.succeed(hitsThroughWire([hit])));
      const { onSelectHit, onOpenChange } = setup();
      await typeQuery('only');
      await settle();

      await waitFor(() => {
        expect(screen.getByText('The only hit')).not.toBeNull();
      });

      // No ArrowDown: with results on screen the top hit must already be the highlighted
      // item. If cmdk leaves the highlight on the Ask row (which is the only item while the
      // query is still being typed), a blind Enter fires an LLM turn instead of opening the
      // top result — the exact thing putting the Ask row last is meant to prevent.
      const input = getInput();
      fireEvent.keyDown(input, { key: 'Enter' });

      expect(onSelectHit).toHaveBeenCalledTimes(1);
      expect(onSelectHit.mock.calls[0]?.[0]).toEqual(hitsThroughWire([hit])[0]);
      // Selecting a hit must also close the dialog — the parent's `onOpenChange(false)`, not
      // just `onSelectHit`.
      expect(onOpenChange).toHaveBeenCalledWith(false);
    });

    const kindCases: ReadonlyArray<{
      kind: string;
      build: () => AiChatApi.SearchHit;
      label: string;
    }> = [
      {
        kind: 'event',
        build: () => eventHit({ title: 'Select-me event' }),
        label: 'Select-me event',
      },
      {
        kind: 'member',
        build: () => memberHit({ displayName: 'Select-me member' }),
        label: 'Select-me member',
      },
      {
        kind: 'group',
        build: () => groupHit({ name: 'Select-me group' }),
        label: 'Select-me group',
      },
      {
        kind: 'roster',
        build: () => rosterHit({ name: 'Select-me roster' }),
        label: 'Select-me roster',
      },
      {
        kind: 'trainingType',
        build: () => trainingTypeHit({ name: 'Select-me tt' }),
        label: 'Select-me tt',
      },
    ];

    for (const { kind, build, label } of kindCases) {
      it(`selecting a ${kind} row calls onSelectHit with exactly that hit`, async () => {
        vi.useFakeTimers();
        const hit = build();
        const wired = hitsThroughWire([hit])[0];
        mockSearch.mockReturnValueOnce(Effect.succeed([wired]));
        const { onSelectHit } = setup();
        await typeQuery('select');
        await settle();

        const row = await waitFor(() => screen.getByText(label));
        const option = row.closest('[role="option"]');
        expect(option).not.toBeNull();
        // biome-ignore lint/style/noNonNullAssertion: asserted non-null above
        fireEvent.click(option!);

        expect(onSelectHit).toHaveBeenCalledTimes(1);
        expect(onSelectHit.mock.calls[0]?.[0]).toEqual(wired);
      });
    }

    // Regression: backspacing a results set all the way back to idle, then typing a fresh,
    // unrelated term, must not leave the highlight (and therefore a blind Enter) pinned on a
    // hit id from the earlier result set that is no longer even rendered.
    it('backspacing a result set down to idle and then typing a new term highlights the NEW first hit, not a stale one', async () => {
      vi.useFakeTimers();
      const firstHit = eventHit({ title: 'First-term hit' });
      const secondHit = eventHit({ title: 'Second-term hit' });
      mockSearch.mockReturnValueOnce(Effect.succeed(hitsThroughWire([firstHit])));
      const { onSelectHit } = setup();

      await typeQuery('items');
      await settle();
      await waitFor(() => {
        expect(screen.getByText('First-term hit')).not.toBeNull();
      });

      // Backspace all the way down to idle (below the 2-char floor) — no rows, no request.
      await typeQuery('i');
      await settle();
      expect(screen.getByText(TR_MAP.search_hint)).not.toBeNull();
      expect(screen.queryByText('First-term hit')).toBeNull();

      mockSearch.mockReturnValueOnce(Effect.succeed(hitsThroughWire([secondHit])));
      await typeQuery('other');
      await settle();
      await waitFor(() => {
        expect(screen.getByText('Second-term hit')).not.toBeNull();
      });

      const input = getInput();
      fireEvent.keyDown(input, { key: 'Enter' });

      expect(onSelectHit).toHaveBeenCalledTimes(1);
      expect(onSelectHit.mock.calls[0]?.[0]).toEqual(hitsThroughWire([secondHit])[0]);
    });
  });

  describe('the Ask row (F.6/16-17)', () => {
    it('selecting the Ask row calls onAskAssistant with the trimmed query', async () => {
      vi.useFakeTimers();
      mockSearch.mockReturnValueOnce(Effect.succeed([]));
      const { onAskAssistant, onOpenChange } = setup();
      await typeQuery('alpha');
      await settle();

      const label = await waitFor(() =>
        screen.getByText(interpolate(TR_MAP.search_askAssistantAbout, { query: 'alpha' })),
      );
      const option = label.closest('[role="option"]');
      expect(option).not.toBeNull();
      // biome-ignore lint/style/noNonNullAssertion: asserted non-null above
      fireEvent.click(option!);

      expect(onAskAssistant).toHaveBeenCalledWith('alpha');
      // Asking must also close the dialog, same as selecting a hit.
      expect(onOpenChange).toHaveBeenCalledWith(false);
    });

    it('a question-shaped query ("?" or >=4 words) uses search_askAssistant, not the "about" phrasing', async () => {
      vi.useFakeTimers();
      setup();
      await typeQuery('who is on the roster?');
      await settle();

      expect(
        screen.getByText(
          interpolate(TR_MAP.search_askAssistant, { query: 'who is on the roster?' }),
        ),
      ).not.toBeNull();
      expect(
        screen.queryByText(
          interpolate(TR_MAP.search_askAssistantAbout, { query: 'who is on the roster?' }),
        ),
      ).toBeNull();
    });

    it('a short name-like query (1-3 words, no "?") uses search_askAssistantAbout', async () => {
      vi.useFakeTimers();
      setup();
      await typeQuery('Novák');
      await settle();

      expect(
        screen.getByText(interpolate(TR_MAP.search_askAssistantAbout, { query: 'Novák' })),
      ).not.toBeNull();
      expect(
        screen.queryByText(interpolate(TR_MAP.search_askAssistant, { query: 'Novák' })),
      ).toBeNull();
    });
  });

  describe('reopen resets both query and debounced state (F.6/20, design §3.5)', () => {
    it('closing and reopening clears the input and renders no stale rows — even within the 250ms debounce window', async () => {
      vi.useFakeTimers();
      const hits = hitsThroughWire([eventHit({ title: 'Stale event' })]);
      mockSearch.mockReturnValueOnce(Effect.succeed(hits));
      const { rerenderWith } = setup({ open: true });

      await typeQuery('stale');
      await settle();
      await waitFor(() => {
        expect(screen.getByText('Stale event')).not.toBeNull();
      });

      rerenderWith({ open: false });
      rerenderWith({ open: true });

      // Immediately on reopen — well before the 250ms debounce could re-settle — there must be
      // no stale row and an empty input. Resetting only `query` (not `debounced`) would still
      // serve "stale" from the React Query cache for up to 250ms; this assertion is taken with
      // NO further timer advance, so it fails under that bug.
      expect(getInput().value).toBe('');
      expect(screen.queryByText('Stale event')).toBeNull();
      expect(screen.getByText(TR_MAP.search_hint)).not.toBeNull();
    });

    // The bug this pins: `placeholderData: (previous) => previous` is keyed per-observer, not
    // per-open-cycle, so the previous session's rows would render under an unrelated new term
    // with NO loading indicator (design §3.5) — and would still be clickable for a full
    // navigation. Reopening resets `query`/`debounced` (covered above), but that alone does not
    // stop `placeholderData` from re-serving the old rows once a new (unrelated) debounced value
    // lands — only a placeholderData that checks the previous/next query are related (a
    // prefix of one another) does.
    it("reopening and typing a brand-new, unrelated term shows loading — not the previous session's stale row", async () => {
      vi.useFakeTimers();
      const hits = hitsThroughWire([eventHit({ title: 'Stale event' })]);
      mockSearch.mockReturnValueOnce(Effect.succeed(hits));
      const { rerenderWith } = setup({ open: true });

      await typeQuery('stale');
      await settle();
      await waitFor(() => {
        expect(screen.getByText('Stale event')).not.toBeNull();
      });

      rerenderWith({ open: false });
      rerenderWith({ open: true });

      mockSearch.mockReturnValueOnce(Effect.never);
      await typeQuery('brandnew');
      await settle();

      expect(screen.queryByText('Stale event')).toBeNull();
      expect(screen.getByText(TR_MAP.search_loading)).not.toBeNull();
    });
  });

  describe('the 100-character input ceiling (F.6/22)', () => {
    it("the input carries maxLength=100, matching the server's `q` bound", () => {
      setup();
      expect(getInput().maxLength).toBe(100);
    });
  });

  describe('accessibility (F.6/23, design §8)', () => {
    it('has exactly one aria-live region, which is a sibling of the listbox (never nested inside it), and no role="status" anywhere in the dialog', async () => {
      vi.useFakeTimers();
      const hits = hitsThroughWire([eventHit({ title: 'A11y event' })]);
      mockSearch.mockReturnValueOnce(Effect.succeed(hits));
      setup();
      await typeQuery('a11y');
      await settle();

      await waitFor(() => {
        expect(screen.getByText('A11y event')).not.toBeNull();
      });

      const dialog = screen.getByRole('dialog');
      const liveRegions = dialog.querySelectorAll('[aria-live]');
      expect(liveRegions).toHaveLength(1);

      const listbox = screen.getByRole('listbox');
      expect(listbox.contains(liveRegions[0] as Node)).toBe(false);

      expect(dialog.querySelectorAll('[role="status"]')).toHaveLength(0);
    });
  });
});
