load_module modules/ngx_http_js_module.so;

worker_processes 4;
worker_rlimit_nofile 2048;

events {
     worker_connections 1024;
}


http {
    include /etc/nginx/conf.d/10-variables.conf;
    include /etc/nginx/conf.d/11-main.conf;

    js_import preview_redirect from /etc/nginx/preview_redirect.js;

    log_format compression '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $upstream_addr '
        '"$http_referer" "$http_user_agent" "$gzip_ratio"';

    server {
        include /etc/nginx/conf.d/12-app.conf;
        server_name _;
        server_tokens off;
        access_log /var/log/nginx/access.log compression;

        resolver 127.0.0.11 valid=10s ipv6=off;

        proxy_ssl_server_name on;
        proxy_ssl_name        $proxy_host;

        set $frontend_url $var_frontend_url;

        location = /api/auth/callback {
            js_content preview_redirect.callback;
        }

        location @server_backend {
            proxy_pass         $var_server_upstream;
            proxy_redirect     off;
            proxy_set_header   Host $proxy_host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $host;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass         $var_server_upstream;
            proxy_redirect     off;
            proxy_set_header   Host $proxy_host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $host;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /otel/ {
            proxy_pass         https://otelcollectorhttp-ccogw4cogg00wwowc0s4c0cs.majksa.net/;
            proxy_redirect     off;
            proxy_set_header   Host otelcollectorhttp-ccogw4cogg00wwowc0s4c0cs.majksa.net;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $host;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location = /docs {
            return 301 /docs/;
        }

        location /docs/ {
            proxy_pass         $var_docs_upstream;
            proxy_redirect     off;
            proxy_set_header   Host $proxy_host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $host;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass         $var_web_upstream;
            proxy_redirect     off;
            proxy_set_header   Host $proxy_host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $host;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }

    server {
        include /etc/nginx/conf.d/13-health.conf;
        server_name _;
        server_tokens off;
        access_log /var/log/nginx/access.log compression;

        location /health {
            default_type application/json;
            return 200 '{"status": "ok"}';
        }
    }
}
