#!/usr/bin/env bash
#
# herdr-worktree.sh — open a branch in an isolated herdr-managed git worktree.
#
# Creates (or reuses) a git worktree for BRANCH via herdr, seeds the gitignored
# config files that a fresh checkout lacks, bootstraps the dev environment
# (direnv + pnpm), and launches a Claude agent inside it.
#
# The machine-generated gitignored dirs (.local/, node_modules/, .direnv/) are
# regenerated by `direnv allow` + `pnpm install` rather than copied — only the
# hand-maintained config files below are seeded.
#
# Usage:
#   scripts/herdr-worktree.sh <branch> [options]
#
# Options:
#   --base <ref>     Base ref for a NEW branch (default: origin/main).
#   --label <text>   Workspace label shown in herdr (default: <branch>).
#   --prompt <text>  Initial prompt the launched Claude runs (e.g. "/work <id>").
#   --no-install     Skip `pnpm install`.
#   --no-agent       Don't launch a Claude agent; just prepare the worktree.
#   -h, --help       Show this help.

set -euo pipefail

die() { printf 'error: %s\n' "$1" >&2; exit 1; }
info() { printf '\033[36m▸ %s\033[0m\n' "$1"; }
warn() { printf '\033[33m! %s\033[0m\n' "$1" >&2; }

# --- config: gitignored files to seed into the fresh worktree ----------------
SEED_PATHS=(
  .env.local
  .env.preview.local
  .claude/settings.local.json
)

# --- arg parsing -------------------------------------------------------------
BRANCH=""
BASE="origin/main"
LABEL=""
PROMPT=""
DO_INSTALL=1
DO_AGENT=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base)       BASE="${2:?--base needs a ref}"; shift 2;;
    --label)      LABEL="${2:?--label needs text}"; shift 2;;
    --prompt)     PROMPT="${2:?--prompt needs text}"; shift 2;;
    --no-install) DO_INSTALL=0; shift;;
    --no-agent)   DO_AGENT=0; shift;;
    -h|--help)    awk 'NR==1{next} /^#/{sub(/^# ?/,"");print;next} {exit}' "$0"; exit 0;;
    -*)           die "unknown option: $1";;
    *)            [[ -z "$BRANCH" ]] && BRANCH="$1" || die "unexpected arg: $1"; shift;;
  esac
done

[[ -n "$BRANCH" ]] || die "branch name is required (usage: $0 <branch> [options])"
command -v herdr >/dev/null || die "herdr CLI not found on PATH"
command -v jq    >/dev/null || die "jq not found on PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
[[ -n "$LABEL" ]] || LABEL="$BRANCH"

# --- 1. create / reuse the worktree ------------------------------------------
info "Fetching origin/main…"
git -C "$REPO_ROOT" fetch origin main --quiet || warn "fetch failed; using local refs"

create_args=(worktree create --cwd "$REPO_ROOT" --branch "$BRANCH" --label "$LABEL" --no-focus --json)
if git -C "$REPO_ROOT" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  info "Branch '$BRANCH' exists — checking it out into a worktree."
else
  info "Creating branch '$BRANCH' from '$BASE'."
  create_args+=(--base "$BASE")
fi

herdr "${create_args[@]}" >/dev/null 2>&1 || warn "worktree create returned non-zero (it may already exist) — resolving by branch."

# Resolve the worktree by branch (schema-independent of `create` output).
# `herdr worktree create` also opens a dedicated workspace for it — capture its
# id so the agent launches INSIDE that workspace, not the caller's.
WT_JSON="$(herdr worktree list --cwd "$REPO_ROOT" --json \
  | jq -c --arg b "$BRANCH" 'first(.result.worktrees[] | select(.branch == $b and .is_linked_worktree == true))')"
WT="$(jq -r '.path // empty' <<<"$WT_JSON")"
WS_ID="$(jq -r '.open_workspace_id // empty' <<<"$WT_JSON")"
[[ -n "$WT" && -d "$WT" ]] || die "could not resolve worktree path for branch '$BRANCH'"
info "Worktree: $WT${WS_ID:+ (workspace $WS_ID)}"

# --- 2. seed gitignored config files -----------------------------------------
for rel in "${SEED_PATHS[@]}"; do
  src="$REPO_ROOT/$rel"
  dst="$WT/$rel"
  if [[ -e "$src" ]]; then
    mkdir -p "$(dirname "$dst")"
    cp -R "$src" "$dst"
    info "Seeded $rel"
  else
    warn "skip $rel (absent in main checkout)"
  fi
done

# --- 3. bootstrap dev environment --------------------------------------------
if command -v direnv >/dev/null; then
  info "direnv allow…"
  direnv allow "$WT" || warn "direnv allow failed"
else
  warn "direnv not found — skipping env load"
fi

if [[ "$DO_INSTALL" -eq 1 ]]; then
  info "pnpm install (this can take a minute)…"
  if command -v direnv >/dev/null; then
    ( cd "$WT" && direnv exec "$WT" pnpm install ) || warn "pnpm install failed"
  else
    ( cd "$WT" && pnpm install ) || warn "pnpm install failed"
  fi
fi

# --- 4. launch the agent -----------------------------------------------------
if [[ "$DO_AGENT" -eq 1 ]]; then
  info "Launching Claude agent in herdr…"

  # Build the `claude` command line, safely quoting the optional prompt.
  # Agents launched here run /work autonomously with no human at the keyboard,
  # so permission prompts would just stall them. Override with CLAUDE_CMD=claude.
  CLAUDE_BASE="${CLAUDE_CMD:-claude --dangerously-skip-permissions}"
  CLAUDE_CMD="$CLAUDE_BASE"
  [[ -n "$PROMPT" ]] && CLAUDE_CMD+=" $(printf '%q' "$PROMPT")"

  # `herdr worktree create` opens the worktree's workspace with a main shell
  # pane. `agent start --workspace` would spawn the agent in a NEW pane beside
  # it (a split). Instead, run `claude` IN that existing main pane so the agent
  # occupies the main pane — no split. Fall back to `agent start` if we can't
  # resolve the main pane.
  MAIN_PANE=""
  if [[ -n "$WS_ID" ]]; then
    MAIN_PANE="$(herdr pane list --workspace "$WS_ID" 2>/dev/null \
      | jq -r '.result.panes[0].pane_id // empty' 2>/dev/null || true)"
  fi

  agent_launched=0
  if [[ -n "$MAIN_PANE" ]]; then
    if herdr pane run "$MAIN_PANE" "$CLAUDE_CMD" >/dev/null 2>&1; then
      herdr pane rename "$MAIN_PANE" "$BRANCH" >/dev/null 2>&1 || true
      [[ -n "$WS_ID" ]] && herdr workspace focus "$WS_ID" >/dev/null 2>&1 || true
      info "Agent '$BRANCH' started in main pane $MAIN_PANE${PROMPT:+ running: $PROMPT}."
      agent_launched=1
    else
      warn "pane run in main pane failed — falling back to agent start."
    fi
  fi

  if [[ "$agent_launched" -eq 0 ]]; then
    start_args=(agent start "$BRANCH" --cwd "$WT" --focus)
    [[ -n "$WS_ID" ]] && start_args+=(--workspace "$WS_ID")
    claude_args=(${CLAUDE_BASE})
    [[ -n "$PROMPT" ]] && claude_args+=("$PROMPT")
    if herdr "${start_args[@]}" -- "${claude_args[@]}"; then
      info "Agent '$BRANCH' started and focused${WS_ID:+ in workspace $WS_ID}${PROMPT:+ running: $PROMPT}."
    else
      warn "agent start failed — open it manually: herdr agent start $BRANCH --cwd \"$WT\"${WS_ID:+ --workspace $WS_ID} -- claude${PROMPT:+ \"$PROMPT\"}"
    fi
  fi
fi

printf '\n\033[32m✓ Worktree ready:\033[0m %s\n' "$WT"
